import { signOut, getSession } from "next-auth/react";

import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { GetServerSideProps } from "next/types";
import useAuth from "../hooks/useAuth";
import styles from "../styles/Home.module.css";

export default function About({ session }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">About world!</h1>
        <button onClick={() => signOut()}>Sign out</button>
        <Link href="/">Home</Link>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const defaultReturnObject = {
    redirect: {
      destination: "/login",
      permanent: false,
    },
  };
  const session = await getSession(ctx);
  if (!session) {
    return defaultReturnObject;
  }
  return { props: { session } };
};
